# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kontak',
        ),
    ]
