# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190815_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilai',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orang',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Nilai',
        ),
        migrations.DeleteModel(
            name='Orang',
        ),
        migrations.DeleteModel(
            name='SPP',
        ),
    ]
